---
name: Sample config
cookie:
  - CFID=20557
  - CFTOKEN=3b79a1e3c773c94-E7F38875-D295-8B7C-22E05E8FB40599AD
testcard:
  number: '5338485258218895'
  expirydate: '3011'
  cvv: '654'
  pin: '1234'
shared:
  amountMin: 1
  amountMax: 6
  defaultOriginalCurrencyCode: '978'
  defaultOriginalCurrencyDecimalPlaces: '2'
  defaultProvince: 'COMPANION'
  defaultCountry: 'VNM'
  defaultMcc: '7299'
testcases:
  - included: false 
    name: ecommerce
    runs: 1 
    mode: web 
    function: 
    atm: false  
    source: 
    foreign: false 
    originalCurrencyCode: 
    originalCurrencyDecimalPlaces: 
    acquirer: ECOM DEDUCT
    province: COMPANION
    country: VNM
    mcc: '7299'
    reversal:
    advice: false 

  - included: true 
    name: pos reversal
    runs: 1 
    mode: pos 
    function: 
    atm: false  
    source: nfc 
    foreign: false 
    originalCurrencyCode: 
    originalCurrencyDecimalPlaces: 
    acquirer: POS DEDUCT REV
    province: 
    country: 
    mcc: '7299'
    reversal: full
    advice: false

  - included: false 
    name: refund
    runs: 1 
    mode: settlement 
    function: refund
    atm: false  
    source: emv 
    foreign: false 
    originalCurrencyCode: 
    originalCurrencyDecimalPlaces: 
    acquirer: REFUND TEST
    province: COMPANION
    country: VNM
    mcc: '7299'
    reversal:
    advice: false  

  - included: false 
    name: fx load adjustment
    runs: 1 
    mode: settlement 
    function: fxload
    atm: false  
    source: 
    foreign: false 
    originalCurrencyCode: 
    originalCurrencyDecimalPlaces: 
    acquirer: FX LOAD TEST
    province: COMPANION
    country: VNM
    mcc: '7299'
    reversal:
    advice: false
  
  - included: false 
    name: fx deduct adjustment
    runs: 1 
    mode: settlement 
    function: fxdeduct
    atm: false  
    source: 
    foreign: false 
    originalCurrencyCode: 
    originalCurrencyDecimalPlaces: 
    acquirer: FX DEDUCT TEST
    province: COMPANION
    country: SGP
    mcc: '7299'
    reversal:
    advice: false
  
  - included: false 
    name: chargeback
    runs: 1 
    mode: settlement 
    function: chargeback
    atm: false  
    source: 
    foreign: false 
    originalCurrencyCode: 
    originalCurrencyDecimalPlaces: 
    acquirer: CHARGEBACK TEST
    province: COMPANION
    country: VNM
    mcc: '7299'
    reversal:
    advice: false